@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODQ0MjkxOTd9.NvYyK4Ig-IWvEG0azHqcbDU4ivUtKQTyrvpCmaLTeyo

POST http://localhost:3000/selected_songs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "song_id": 1,
  "set_list_id": 2
}

###

GET http://localhost:3000/selected_songs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json