@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODQzNTQyNjJ9.A-gXYmFmvHu5aqwfFVO2pt5wK42hMlpYcSjvURFAgEQ

POST http://localhost:3000/selected_songs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "song_id": 1,
  "set_list_id": 1
}

###

GET http://localhost:3000/selected_songs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json