@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODQzNTQyNjJ9.A-gXYmFmvHu5aqwfFVO2pt5wK42hMlpYcSjvURFAgEQ

POST http://localhost:3000/set_lists.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

###

GET http://localhost:3000/set_lists/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json


###

GET http://localhost:3000/set_lists.json
Authorization: Bearer {{jwt}}
Content-Type: application/json
